name: Make release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git Reference'
        required: true
        default: 'master'
      tag:
        description: 'Tag to create'
        required: true


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - run: make soju GOFLAGS="-tags=libsqlite3" # -ldflags="-s -w"

      - name: Make a release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ inputs.ref }}
          tag_name: ${{ inputs.tag }}
          prerelease: true
          files: |
            soju
            sojudb
            sojuctl
